interface ToolInfoSectionProps {
  title: string;
  description: string;
  howToUse?: string[];
  benefits?: string[];
  faqs?: { q: string; a: string }[];
}

const defaultContent = {
  howToUse: [
    "Fill in the required input fields on the left panel with your details.",
    "Adjust any optional settings such as tone, length, or format to match your needs.",
    "Click the generate button and wait a moment for the AI to process your request.",
    "Review the generated output in the results panel on the right.",
    "Copy your favorite result with one click and paste it directly where you need it.",
    "Generate again for fresh variations if you want different options.",
  ],
  benefits: [
    "Saves hours of manual writing and brainstorming time every week.",
    "Produces professional-quality content without needing copywriting expertise.",
    "Generates multiple unique variations for every input so you always have options.",
    "Completely free to use — no signup, no credit card, no usage limits.",
    "Powered by advanced AI models trained on billions of pieces of high-performing content.",
    "Results are instant — get usable copy in seconds, not hours.",
  ],
};

export function ToolInfoSection({ title, description, howToUse, benefits, faqs }: ToolInfoSectionProps) {
  const steps = howToUse ?? defaultContent.howToUse;
  const perks = benefits ?? defaultContent.benefits;

  const defaultFaqs = [
    {
      q: `Is the ${title} completely free to use?`,
      a: `Yes, ToolsAI's ${title.toLowerCase()} is 100% free with no hidden fees, no usage limits, and no account required. Just enter your details and generate professional content instantly.`,
    },
    {
      q: `How accurate is the AI-generated content from this tool?`,
      a: `Our AI produces high-quality, contextually relevant content using advanced language models. Results are typically ready to use with minimal editing. We recommend reviewing the output once before publishing to ensure it matches your exact brand voice.`,
    },
    {
      q: `Can I use the generated content for commercial purposes?`,
      a: `Yes. Content generated by ToolsAI can be used freely for both personal and commercial projects including blogs, social media, advertising, and client work. We recommend adding your own unique perspective to make the content truly yours.`,
    },
  ];

  const faqList = faqs && faqs.length > 0 ? faqs : defaultFaqs;

  return (
    <div className="mt-16 space-y-10 border-t border-border pt-12">
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        <div>
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <span className="w-6 h-1 bg-primary rounded-full"></span>
            How to Use the {title}
          </h2>
          <p className="text-muted-foreground mb-6 leading-relaxed">
            Using ToolsAI's {title.toLowerCase()} is fast, free, and requires no technical knowledge. Follow these simple steps to get the best results from our AI:
          </p>
          <ol className="space-y-4">
            {steps.map((step, i) => (
              <li key={i} className="flex items-start gap-4">
                <span className="flex-shrink-0 w-7 h-7 rounded-full bg-primary/10 text-primary text-sm font-bold flex items-center justify-center border border-primary/20">
                  {i + 1}
                </span>
                <p className="text-muted-foreground leading-relaxed pt-0.5">{step}</p>
              </li>
            ))}
          </ol>
        </div>

        <div>
          <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
            <span className="w-6 h-1 bg-accent rounded-full"></span>
            Why Use ToolsAI's {title}?
          </h2>
          <p className="text-muted-foreground mb-6 leading-relaxed">
            {description} Our AI tool gives you a significant productivity advantage over creating content manually. Here's why thousands of creators, marketers, and writers trust ToolsAI:
          </p>
          <ul className="space-y-3">
            {perks.map((perk, i) => (
              <li key={i} className="flex items-start gap-3">
                <span className="mt-1.5 w-2 h-2 rounded-full bg-accent shrink-0"></span>
                <p className="text-muted-foreground leading-relaxed">{perk}</p>
              </li>
            ))}
          </ul>
        </div>
      </div>

      <div>
        <h2 className="text-2xl font-bold text-foreground mb-6 flex items-center gap-3">
          <span className="w-6 h-1 bg-primary rounded-full"></span>
          Frequently Asked Questions
        </h2>
        <div className="space-y-4">
          {faqList.map((faq, i) => (
            <div key={i} className="bg-white border border-border rounded-2xl p-5 hover:border-primary/20 transition-colors">
              <h3 className="font-semibold text-foreground mb-2">{faq.q}</h3>
              <p className="text-muted-foreground text-sm leading-relaxed">{faq.a}</p>
            </div>
          ))}
        </div>
      </div>

      <div className="bg-gradient-to-r from-primary/5 to-accent/5 border border-primary/10 rounded-3xl p-8 text-center">
        <h3 className="text-xl font-bold text-foreground mb-3">Explore More Free AI Tools</h3>
        <p className="text-muted-foreground mb-5 max-w-xl mx-auto">
          ToolsAI offers 20+ free tools for content creators, writers, marketers, and developers. From social media captions to SEO meta tags — there's a tool for every creative need.
        </p>
        <a href="/" className="inline-block bg-gradient-to-r from-primary to-accent text-white font-bold py-3 px-8 rounded-xl shadow-lg shadow-primary/20 hover:opacity-90 transition-opacity">
          Browse All Tools
        </a>
      </div>
    </div>
  );
}
