import { ReactNode } from "react";
import { AlertTriangle } from "lucide-react";
import { motion } from "framer-motion";

const Section = ({ title, children }: { title: string; children: ReactNode }) => (
  <div className="space-y-3">
    <h2 className="text-xl font-bold text-foreground">{title}</h2>
    <div className="text-muted-foreground leading-relaxed space-y-3">{children}</div>
    <hr className="border-border" />
  </div>
);

export default function Disclaimer() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="max-w-3xl mx-auto pb-16"
    >
      <div className="text-center mb-10">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-amber-100 to-orange-50 text-amber-600 mb-6 shadow-inner border border-amber-100">
          <AlertTriangle className="w-8 h-8" />
        </div>
        <h1 className="text-4xl font-bold text-foreground mb-3">Disclaimer</h1>
        <p className="text-muted-foreground">Last updated: March 18, 2026</p>
      </div>

      <div className="bg-white/80 backdrop-blur-xl border border-white/50 shadow-xl shadow-primary/5 rounded-3xl p-8 md:p-12 space-y-8">
        <p className="text-muted-foreground leading-relaxed">
          This Disclaimer governs the use of ToolsAI, accessible at toolsai.app. By using ToolsAI, you accept this Disclaimer in full. If you disagree with any part of this Disclaimer, do not use ToolsAI.
        </p>

        <Section title="1. AI-Generated Content Disclaimer">
          <p>All content generated by ToolsAI's AI tools is produced automatically by artificial intelligence systems. While we strive to provide high-quality, relevant outputs, we make no guarantees regarding the accuracy, completeness, reliability, suitability, or availability of any AI-generated content.</p>
          <p>AI-generated content may:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Contain factual inaccuracies or outdated information</li>
            <li>Reflect biases present in the underlying AI training data</li>
            <li>Produce repetitive or generic content not suited for every use case</li>
            <li>Generate content that requires significant editing before professional use</li>
            <li>Occasionally produce content that is irrelevant, nonsensical, or off-topic</li>
          </ul>
          <p>You are solely responsible for reviewing, editing, and verifying any AI-generated content before using it for professional, commercial, legal, medical, or any other purposes.</p>
        </Section>

        <Section title="2. No Professional Advice">
          <p>The content and tools provided on ToolsAI are for informational and creative assistance purposes only. Nothing on this website should be construed as professional legal, medical, financial, marketing, or any other type of professional advice. Always consult a qualified professional before making decisions based on AI-generated content.</p>
        </Section>

        <Section title="3. No Guarantee of Results">
          <p>ToolsAI provides tools designed to assist with content creation, marketing, and productivity. However, we make no guarantees regarding the commercial success, effectiveness, or performance of any content generated using our tools. Results from using AI-generated content will vary based on many factors outside our control, including how the content is used, the target audience, platform algorithms, and market conditions.</p>
        </Section>

        <Section title="4. Third-Party Content and Links">
          <p>Our website may contain links to external websites or resources that are not provided or maintained by, or in any way affiliated with, ToolsAI. We do not guarantee the accuracy, relevance, timeliness, or completeness of any information on these external websites. We have no control over the nature, content, and availability of those sites and shall not be liable for any loss or damage arising from their use.</p>
        </Section>

        <Section title="5. Copyright and Plagiarism">
          <p>While our AI tools generate original content, we cannot guarantee that all generated outputs are entirely unique or free from resemblance to existing copyrighted material. You are responsible for ensuring that any AI-generated content you publish does not infringe upon third-party intellectual property rights. We recommend running all generated content through a plagiarism checker before publication.</p>
        </Section>

        <Section title="6. Service Availability">
          <p>We endeavor to keep ToolsAI operational at all times. However, we do not warrant that the website will be available at all times, error-free, or free of viruses or other harmful components. We reserve the right to suspend or terminate the Service at any time without notice.</p>
        </Section>

        <Section title="7. Limitation of Liability">
          <p>To the fullest extent permitted by law, ToolsAI and its operators shall not be held responsible for any losses or damages incurred as a result of using AI-generated content from this website, including but not limited to direct, indirect, incidental, punitive, and consequential damages.</p>
        </Section>

        <div className="space-y-2">
          <h2 className="text-xl font-bold text-foreground">8. Contact</h2>
          <p className="text-muted-foreground">Questions about this Disclaimer? Contact us at <a href="mailto:legal@toolsai.app" className="text-primary hover:underline font-medium">legal@toolsai.app</a>.</p>
        </div>
      </div>
    </motion.div>
  );
}
