import { ReactNode } from "react";
import { FileText } from "lucide-react";
import { motion } from "framer-motion";

const Section = ({ title, children }: { title: string; children: ReactNode }) => (
  <div className="space-y-3">
    <h2 className="text-xl font-bold text-foreground">{title}</h2>
    <div className="text-muted-foreground leading-relaxed space-y-3">{children}</div>
    <hr className="border-border" />
  </div>
);

export default function TermsOfService() {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.3 }}
      className="max-w-3xl mx-auto pb-16"
    >
      <div className="text-center mb-10">
        <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-primary/20 to-accent/10 text-primary mb-6 shadow-inner border border-primary/10">
          <FileText className="w-8 h-8" />
        </div>
        <h1 className="text-4xl font-bold text-foreground mb-3">Terms of Service</h1>
        <p className="text-muted-foreground">Last updated: March 18, 2026</p>
      </div>

      <div className="bg-white/80 backdrop-blur-xl border border-white/50 shadow-xl shadow-primary/5 rounded-3xl p-8 md:p-12 space-y-8">
        <p className="text-muted-foreground leading-relaxed">
          Please read these Terms of Service ("Terms") carefully before using the ToolsAI website located at toolsai.app (the "Service") operated by ToolsAI ("us", "we", or "our"). Your access to and use of the Service is conditioned on your acceptance of and compliance with these Terms. These Terms apply to all visitors, users, and others who access or use the Service.
        </p>

        <Section title="1. Acceptance of Terms">
          <p>By accessing or using our Service, you agree to be bound by these Terms. If you disagree with any part of the terms, then you may not access the Service. We reserve the right to update or change our Terms at any time and it is your responsibility to check these Terms periodically for changes.</p>
        </Section>

        <Section title="2. Description of Service">
          <p>ToolsAI provides a suite of AI-powered and utility tools designed for content creators, marketers, writers, and general users. Our tools include, but are not limited to, AI text generators, writing assistants, hashtag generators, SEO tools, and developer utilities. The Service is provided free of charge and is supported by advertising revenue.</p>
        </Section>

        <Section title="3. Acceptable Use">
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>Generate content that is illegal, harmful, threatening, abusive, harassing, defamatory, or otherwise objectionable</li>
            <li>Generate spam, misleading information, or deceptive content intended to mislead others</li>
            <li>Violate any applicable local, national, or international law or regulation</li>
            <li>Infringe upon the intellectual property rights of any party</li>
            <li>Attempt to gain unauthorized access to any part of our systems or infrastructure</li>
            <li>Use automated scripts or bots to access the Service in a manner that places excessive load on our servers</li>
          </ul>
          <p>We reserve the right to terminate or restrict access for users who violate these acceptable use guidelines.</p>
        </Section>

        <Section title="4. AI-Generated Content">
          <p>The content generated by our AI tools is produced algorithmically and may not always be accurate, complete, or suitable for all purposes. You acknowledge that:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>AI-generated content should be reviewed and edited before professional use</li>
            <li>We do not guarantee the accuracy, reliability, or quality of AI-generated outputs</li>
            <li>You are solely responsible for how you use the AI-generated content</li>
            <li>Generated content may occasionally contain errors, biases, or outdated information</li>
          </ul>
        </Section>

        <Section title="5. Intellectual Property">
          <p>The Service and its original content (excluding content provided by users), features, and functionality are and will remain the exclusive property of ToolsAI. Our trademarks and trade dress may not be used in connection with any product or service without prior written consent.</p>
          <p>You retain all ownership rights to the content you input into our tools. Content generated as output by our AI tools is provided to you for your personal and commercial use, subject to these Terms.</p>
        </Section>

        <Section title="6. Advertising">
          <p>The Service is ad-supported. By using the Service, you consent to the display of advertisements, including personalized advertising served by third-party ad networks such as Google AdSense. You may opt out of personalized advertising through your browser or ad network settings.</p>
        </Section>

        <Section title="7. Disclaimer of Warranties">
          <p>The Service is provided on an "AS IS" and "AS AVAILABLE" basis without any warranties of any kind, either express or implied, including but not limited to implied warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or free of viruses or other harmful components.</p>
        </Section>

        <Section title="8. Limitation of Liability">
          <p>To the maximum extent permitted by applicable law, in no event shall ToolsAI, its directors, employees, partners, agents, suppliers, or affiliates, be liable for any indirect, incidental, special, consequential, or punitive damages, including without limitation loss of profits, data, or goodwill, arising out of or related to your use of the Service.</p>
        </Section>

        <Section title="9. Governing Law">
          <p>These Terms shall be governed and construed in accordance with applicable law, without regard to its conflict of law provisions. Any disputes arising under these Terms shall be subject to the exclusive jurisdiction of the applicable courts.</p>
        </Section>

        <div className="space-y-2">
          <h2 className="text-xl font-bold text-foreground">10. Contact Us</h2>
          <p className="text-muted-foreground">If you have any questions about these Terms, please contact us at <a href="mailto:legal@toolsai.app" className="text-primary hover:underline font-medium">legal@toolsai.app</a>.</p>
        </div>
      </div>
    </motion.div>
  );
}
